FROM node:21.7.1-alpine3.19

# Create app directory
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
ADD wasm-lib wasm-lib

# Actualizo los paquetes de alpine
RUN apk update && apk upgrade

# Rust
RUN apk add --no-cache \
    rust \
    cargo \
    wasm-pack

# Build wasm module
RUN npm run build:wasm

RUN npm install --verbose
COPY . .

# Paquetes para desarrollo con vscode
RUN apk add --no-cache \
    nano \
    git \
    vim \
    rust-analyzer; 

CMD npm run dev
