name: Staging test workflow

on:
  pull_request:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cd wasm-lib && cargo +nightly test
      - run: cd wasm-lib && cargo +nightly fmt
      - run: cd wasm-lib && cargo +nightly clippy
