name: Staging test workflow

on:
  pull_request:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd wasm-lib && cargo test
      - run: cd wasm-lib && cargo fmt
      - run: cd wasm-lib && cargo clippy
