name: Staging test workflow

on:
  pull_request:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cd wasm-lib && cargo test
      - run: cd wasm-lib && cargo fmt
      - run: cd wasm-lib && cargo clippy
